### ISSUE TITLE
Sales Rep - Invoice Inquiry - Review date selection issue

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#146]
@j120foredeck reported our date selector on on this Bezl seems to be offsetting the range returned by the query by one date.  @NDMO check to see if this is something on our end or not.  It is possible this is due to the difference in between SQL Server DateTime columns versus the Date value this widget would be supplying.

**Comment by NDMO** [comment]
@aellis @j120foredeck , This looks like a display issue to me.  On my end, the date pipe is displaying a different date than what is stored.  e.g. a stored date with the value "2017-01-30T00:00:00" is being displayed as Jan. 29, 2017.  
This is because the original date is expressed in UTC time, and when converted to our local time, it becomes Jan 29, 2017 7pm.  
Does this sound like what you are seeing?  A good way to determine is to copy this line of code to the top of the html. This will show what is returned from the table.
<pre>{{bezl.data.Invoices | json}}</pre>
Then Select a small portion of invoices using a short period of time.
Compare the stored date to the displayed date.

**Comment by j120foredeck** [comment]
Note that the source query for OrderInquiry was changed to format the order date as follows:
	convert(varchar,o.ORDER_DATE,101) As OrderDate,
...and now the data displays as expected. The same format convert was already in place for InvoiceInquiry.

**Comment by aellis** [comment]
For posterity sake, @OnlyAGhost had some notes on this that may be useful down the road when converting the data from the query into UTC - it goes the other way and converts the date picker value from UTC to local:

```
In Bezlio (really any Angular2 binding to a date input) there is an issue with internationalization where if you select a date it can select the day before instead. My understanding is that its an issue between UTC and local time zones, but here is how you can fix it.

In ngOnInit I create 2 new functions, a parse date and a get date function:

bezl.functions.parseDate = function(datestring) {
  datestring = datestring.split('-');
  return new Date(datestring[0], datestring[1]-1, datestring[2]);
};

bezl.functions.getDate = function(d) {
  return d.toISOString().substring(0, 10);
};

Then instead of binding with [(ngModel)] you bind the get and set values separately:
<input type="date" [value]="bezl.functions.getDate(bezl.vars.OrderDate)" (input)="bezl.vars.OrderDate = bezl.functions.parseDate($event.target.value)">

```
