### ISSUE TITLE
Sales Rep - Order Inquiry - UI Revisions For Mobile HIGH PRIORITY

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#174]
The Order Inquiry could use some revisions to make it display better on mobile:

- The 'Order Amount' sort by button does not align on the left hand side with the 'Order Date' button.
- The text 'Order Amount' is very tight.  Abbreviate this to 'Order Amt'
- Expand the width of the sort buttons so they don't grow when you sort on them.
- On the drill-down, the headings don't really make sense how we have them.  Switch this *for mobile only* to be inline labels before each value.  For example:

Line #: 1
Part #: XYZ123
Description: This is a description

Use a div layout so that the labels and values are consistently formatted.  Further, the drill-down has these labeled as 'Sort By' but you cannot click any of them.  I would suggest just replacing that entire area with a label that says 'Lines' and stick with our inline labels.

- When sorting on the order amount, descending has $0 first.  The sorting logic needs to correctly place these at the bottom.
- Sorting on the PO # column does not appear to do anything.
- On the mobile layout, add the column names inline with the values similar to how was described for the drill-down.

**Comment by NDMO** [comment]
@aellis Hey it looks like sorting the PO# doesn't work properly because we have it sorting as a number and some of our examples have text in them. If the PO# only contain numbers it will sort correctly.  Do you want me to switch the sort to alphabetical instead? I guess I am just unsure if customers will have letters in their PO#s
