### ISSUE TITLE
All - App Versioning

### ISSUE THREAD

**Issue by bitingmidge** [bezlio/bezlio-apps#232]
## Issue

Apps consist of:

- a bezl (and it's associated markup and code)
- included Javascript files that are hosted elsewhere
- backend SQL scripts

The bezl and Javascript includes are especially tightly coupled but can be updated independent of each other which can break apps if the right versions of both aren't being used together. The SQL scripts could also include changes that would be necessary for a specific version of an app. Right now there is no versioning built into either side of the equation which this issue aims to address.

## Requirements

- Allow an app's bezl, Javascript, and SQL to be pegged to a specific version number
- Allow app's version numbers to be independent of each other. (e.g. app A is version 1.1 and App B is version 1.23)
- Allow the current infrastructure of Production (master) and Testing (development) environments to continue
- Allow a hot fix to a specific version to be rolled out
- Do not break existing bezels in production that are not versioned

## Future Considerations

- The Bezlio App Store will eventually be dynamically built based on a mapping file that will define the apps, versions, and location of installation files
- Users may eventually be able to install / upgrade / downgrade specific app versions from the Bezlio App Store

## Unknowns

- Do the library scripts need their own version numbers? (i.e. Epicor, Excel, etc..) I'm thinking they may.

## Proposal

- The current link between the master branch and the https://bezlio-apps.bezl.io azure hosting will be removed leaving the Javascript includes hosted there at their current unversioned state. All existing unversioned copies of bezels in production currently point to that URL essentially freezing them in time. No further updates will be made to the https://bezlio-apps.bezl.io domain. Eventually use of unversioned apps will reduce through attrition and the hits here could eventually be monitored and decommissioned when no longer necessary. That is down the road though.
-  In the setConfig() function of all apps the following will be added: bezl.vers.config.version = "1.x"; This will peg the bezl at that particular version.
- The code in setConfig() that dynamically sets the basePath will be dynamically set depending on the version number.
- When a new version number is made a copy of the Javascript and SQL will be placed in a subfolder named for the version number. For example, under the "roles/sales-rep/accounts-view" app you would have the current development version of the files as well as separate folders for each specific version:

BezlExport.txt
js/...
sql/...

    1.1/
            BezlExport.txt
            js/...
            sql/...

    1.2/
            BezlExport.txt
            js/...
            sql/...

    1.3/
            BezlExport.txt
            js/...
            sql/...

- When bezl.vers.config.version = "" (empty string) that indicates the current development version (HEAD). So during development the first step after importing the app is to set the version to an empty string.

## Version Numbering Scheme

The version numbering will follow a simple MAJOR.MINOR scheme where the MAJOR would be updated rarely and standard basic releases from development to production increment the MINOR number.

e.g. 1.23

**Comment by bitingmidge** [comment]
@aellis @OnlyAGhost - Probably missed something but this is open for input and suggestions now.

**Comment by aellis** [comment]
@bitingmidge - I have owed you a reply on this one.  Everything you have here looks solid to me.  I would add the following:

- I concur that the libraries should also be versioned and that they will have their own versioning.  For that reason, you may also need some indication of the library version in setConfig.  That or we just do away with having the libraries be common like they are and instead accept the bit of code duplication and just pull them into the individual apps.  We could keep the library folder out there but it would act more as code snippets you can pull into your apps.  I feel like I lean towards this approach so we have one less version number to keep in mind.

- With regards to the migration, as noted we will disconnect https://bezlio-apps.bezl.io so it no longer receives any updates from github (in order to avoid our restructure from introducing breaking changes to existing deployments).  @ejremington - could you configure https://apps.bezl.io and https://apps-dev.bezl.io which will reflect our new app deployment servers?

**Comment by aellis** [comment]
See issue #264.

**Comment by bitingmidge** [comment]
@aellis I'm considering putting all of the versions inside of a single subdirectory called "versions" (e.g. bezlio-apps/roles/sales-rep/accounts-view/**versions**/1.0). Seems a little less cluttered and more organized perhaps? What do you think?
