### ISSUE TITLE
Sales Rep - Accounts View - Prepopulate CRM Call Details On Click To Dial / Email / Navigate

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#25]
On sales-rep.accounts-view we have it set up where phone numbers, e-mail addresses, and street addresses are hyperlinks that perform actions.  Upon clicking on any of these, it is desired to automatically add a CRM call entry as per the following:

Clicking Phone Number:
Short Summary: Phone Call To [Contact Name]
Call Type: Phone Call (only if this is a valid call type, otherwise leave blank)

Clicking E-mail Address:
Short Summary: E-mail To [Contact Name]
Call Type: E-mail (only if this is a valid call type, otherwise leave blank)

Clicking Address:
Short Summary: Customer Visit
Call Type: Customer Visit (only if this is a valid call type, otherwise leave blank)

Now currently the shortSummary, details, and type are all bound to the bezl.vars of the CRM Calls View Bezl itself which would make it difficult to update directly (could be done - would just require the whole jQuery signaling).  The easier fix here is simply to change the bindings in CRM Calls View as follows:

bezl.vars.shortSummary => bezl.vars.selectedAccount.shortSummary
bezl.vars.details => bezl.vars.selectedAccount.details
bezl.vars.type => bezl.vars.selectedAccount.type

With this change, you should simply be able to write these entries within accounts-view and re-fire the selected account change.

**Comment by aellis** [comment]
One more note - you may not need to re-fire the selected account change either - test and see first.  Sometimes this change detection works better than I could imagine.

**Comment by bitingmidge** [comment]
@aellis - Just a thought as I'm doing this... Is the verbiage "CRM Call" specific to Epicor or a standard industry term? Since we are including such things as emails and site visits beyond just phone calls, it would seem like something like "Interaction" (as in "Customer Interaction" or "Account Interaction") would better describe the whole range of communication that is being captured.

**Comment by bitingmidge** [comment]
@aellis @OnlyAGhost  - In debugging this issue I discovered that the jQuery .trigger() events that we have been using are firing multiple times because they are being bound to all objects in the DOM that have the CSS class ".panel" attached to them, like so:

$(".panel").on("selectAccount", function(event, param1)...

Every bezl on a panel uses the CSS class .panel (as well as some other objects) so in my particular example the event handler code is being called seven times when it only needs to be called once.

Is there a better object ID or CSS class that we could be using to bind to that should only exist once per panel?

**Comment by OnlyAGhost** [comment]
I would suggest adding one to
Bezlpanel.component.html

At the top, add an additional class or id that we can bind to that would be unique.

[SaberLogic]<http://www.saberlogic.com/>

brian ellis

sales manager

[http://www.saberlogic.com/images/M_images/sl-icon-linkedin-orange.png]<https://www.linkedin.com/in/brianmellis/>

[http://www.saberlogic.com/images/M_images/sl-icon-facebook-orange.png]<https://www.facebook.com/bezlio/>

[http://www.saberlogic.com/images/M_images/sl-icon-twitter-orange.png]<https://twitter.com/Bezlio>

[http://www.saberlogic.com/images/M_images/sl-icon-google-orange.png]<https://plus.google.com/u/2/b/115934345355823038480/115934345355823038480?pageId=115934345355823038480>

[http://www.saberlogic.com/images/M_images/sl-icon-youtube-orange.png]<https://www.youtube.com/channel/UCVGUTpZafTKMG6-gpDe-UkA>






[http://www.saberlogic.com/images/M_images/sl-icon-addresspin-orange.png]

132 main street, wadsworth, oh 44281


[http://www.saberlogic.com/images/M_images/sl-icon-phonehandset-orange.png]

+1 (855) 335-6442 x105<tel:>


[http://www.saberlogic.com/images/M_images/sl-icon-webglobe-orange.png]

www.saberlogic.com<http://www.saberlogic.com>




[Bezlio - Do you want a customer portal?]<https://bezl.io/>
